name: 🐛 Bug
description: Report an issue to help improve the project.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug that you found!
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false

  - type: textarea
    id: desktop
    attributes:
      label: Desktop (please complete the following information)
      description: Please add the details of your desktop -> OS, Browser, Version
    validations:
      required: false

  - type: textarea
    id: smartphones
    attributes:
      label: Smartphone (please complete the following information)
      description: Please add the details of your Smartphone -> Device, OS, Browser, Version
    validations:
      required: false

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I have checked the existing issues
        - label: I'm a GSSoC'23 contributor
        - label: I want to work on this issue
