name: Other
description: Use this for any other issues. Please do NOT create blank issues
title: "[OTHER]"

body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
    label: 'Record'
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
      - label: I have checked the existing issues  
      - label: I'm a GSSoC'23 contributor
      - label: I want to work on this issue     
